### ISSUE TITLE
Error with build.py file

### ISSUE THREAD

**Issue by marioalfaro75** [awslabs/amazon-rekognition-video-analyzer#2] opened 2017-09-11 14:51 UTC
Hi,

I am trying to run pynt -l and I am getting an syntax error:

  File "build.py", line 25
    print 'zipping %s as %s' % (os.path.join(dirname, filename),
                                        ^
SyntaxError: invalid syntax

Looking at the code in build.py the For loop does not seem to be complete.  Could you please assist, thanks.

**Comment by moanany** [comment] 2017-09-11 15:30
Hi there,

I could not reproduce this error. The code for this loop is complete. This statement, however, is completed on a new line. Could this be the cause in your case?

Thanks,
Moataz

**Comment by adrianmelic** [comment] 2017-09-30 10:42
Maybe you are using Python 3. 
That was my mistake.

**Comment by moanany** [comment] 2017-11-03 02:40
@marioalfaro75 Closing this issue. Please post any updates/questions and I'll re-open.

**Closed by moanany** 2017-11-03 02:40 UTC

**Comment by poornimasivakumar** [comment] 2017-12-05 06:35
Hi @adrianmelic  @moanany 
I'm getting the same issue.
`
C:\face>pynt -l
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\pynt.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\pynt\_pynt.py", line 295, in main
    build(sys.argv[1:])
  File "c:\python36\lib\site-packages\pynt\_pynt.py", line 48, in build
    module = imp.load_source(path.splitext(path.basename(args.file))[0], args.fi
le)
  File "c:\python36\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "build.py", line 25
    print 'zipping %s as %s' % (os.path.join(dirname, filename),
                           ^
SyntaxError: invalid syntax`


@adrianmelic  how did you fix it?


Thanks a ton!

**Comment by adrianmelic** [comment] 2017-12-16 00:10
@poornimasivakumar I just used Python 3 and not Python 2.7.

**Comment by sujithaperumal** [comment] 2019-02-16 05:36
hi @adrianmelic I'm using python 3.7 and I still the same issue. Any help would be appreciated. Thanks!

**Comment by adrianmelic** [comment] 2019-02-22 18:19
Sorry @sujithaperumal it has been so long that I don't even remember this issue :(

**Comment by rodalarcon** [comment] 2019-05-22 02:38
The code was developed for Python 2.7. For Python 3 the following changes should be made:

On build.py:
1) Ensure the argument for all the print calls is inside parenthesis, i.e., print('zipping %s as %s' % (os.path.join(dirname, filename))
2) Replace SimpleHTTPServer by http.server, at import and in the webuiserver function
3) Replace SocketServer by socketserver, at import and in the webuiserver function
4) Replace 'iteritems' by 'items' on lines 160 and 200 for the dict() attribute.

On /client/video_cap_ipcam.py:
1) Ensure the argument for all the print calls is inside parenthesis, i.e., print("Sending image to Kinesis")

On /client/video_cap.py:
1) Ensure the argument for all the print calls is inside parenthesis, i.e., print("Sending image to Kinesis")
