### ISSUE TITLE
pynt webui:

### ISSUE THREAD

**Issue by anandpanchal** [awslabs/amazon-rekognition-video-analyzer#8] opened 2017-11-29 06:24 UTC
hi,

pynt webui giving error: an error occured when calling the describestackresource operation: resource vidanalyzerrestapi does not exist for stack video-analyzer-stack.

please help me

Thanks

**Comment by moanany** [comment] 2017-12-01 14:13
Closing this as duplicate of #9. Will comment over there.

**Closed by moanany** 2017-12-01 14:13 UTC
