### ISSUE TITLE
pynt createstack failed

### ISSUE THREAD

**Issue by stardev24** [awslabs/amazon-rekognition-video-analyzer#3] opened 2017-10-14 16:25 UTC
pynt createstack failed because of Status reason:
The following resource(s) failed to delete: [EnrichedFrameTable] in cloudformation.Help needed.

**Comment by moanany** [comment] 2017-10-15 02:11
Hello!

This could happen when one of the stack's resources fail to create, so, CloudFormation attempts to roll back the stack creation immediately. The rollback process may fail to delete the DynamoDB table if it was still being created when rollback executes.

I'd suggest the following:

1) Find out which resources are failing to create and why from the "Events" section in the CloudFormation console. Address the root cause of failure. 

A common cause, for example, is that the commands "pynt package lambda" and then "pynt deploy lambda" were not issued prior to "pynt createstack", and thus, an S3 bucket used by the CloudFormation stack was not found. This leads to stack creation failure. It could also lead to stack rollback failure, if the DynamoDB table was still being created.

2) Check stack status in the CloudFormation console. The stack status may be either "ROLLBACK_COMPLETE" or "ROLLBACK_FAILED" at this point. Manually delete the stack.

3) Re-run "pynt createstack" after the root cause identified in step 1 is addressed.

I'll keep this issue open in the meantime.

**Comment by stardev24** [comment] 2017-10-15 17:48
HI,

Thanks for quick response.I have created lambda package and deployed to s3 bucket.But after that only I am using pynt createstack.Here by providing the logs
![create package error](https://user-images.githubusercontent.com/13711150/31587418-22b88c58-b1ff-11e7-95da-236bf2126071.png)

Looking forward for your support.

**Comment by stardev24** [comment] 2017-10-15 17:56
I have tried multiple times manual stack deletion and executing the create stack command.But every time I am getting status as ROLLBACK_FAILED.
Hope the logs provided above will help you to understand the issue.

**Comment by moanany** [comment] 2017-10-15 19:20
Hello,

To fix this, delete _FrameFetcherLambdaExecutionRole_ (along with _ImageProcessorLambdaExecutionRole_ if it exists, too) using the IAM console. From the event log you shared, CloudFormation attempts to create the role while it already exists. This could happen, for example, if you attempted to create the stack in another region. IAM resources are global and the roles have names (RoleName attribute) in the CFN template.

A temporary solution is to delete those already-created resources manually from your account using the IAM console. You can also manually delete the stack from other regions. Then, recreate the stack.

A better fix would be to either omit RoleName in the CFN template (simply commenting out or removing the property from both execution roles). I do have to update and test the CFN template before pushing such an change to this repo. You may want to give it a try in the meantime.

**Comment by stardev24** [comment] 2017-10-18 07:28
Hello,

    I have tried the above mentioned way,But same problem.Can you please recheck the Cloudformation template and push to git so that it will be very useful.Kindly help as soon as possible.

Thanks

**Comment by moanany** [comment] 2017-10-18 11:21
Hello,

To help us understand what’s going on, could you please post screenshots of the CFN event log during attempted deletion, after you manually deleted the resources pointed out above?

Thanks.

**Comment by moanany** [comment] 2017-11-03 02:39
I updated the CloudFormation template for more resiliency to resource creation failures. Closing this issue for now. Please feel free to post any additional questions/updates and I'll re-open.

**Comment by stardev24** [comment] 2017-11-03 07:24
Thanks,Let me check and if problem exist I will get back to you.

**Comment by lhamregit** [comment] 2017-11-28 21:17
I tried the same steps as stardev24 and got the exact same result. Looked through the comments and did everything that was recommended (like checking the roles in IAM). Everything is according to the instructions and still seeing the error when creating.

**Comment by moanany** [comment] 2017-11-28 21:45
Hello,

Can you post the details of the error? Screenshots and error message(s) would help.

Thanks

**Comment by lhamregit** [comment] 2017-11-28 22:41
![screen shot 2017-11-28 at 5 40 06 pm](https://user-images.githubusercontent.com/1796077/33348174-46e221bc-d463-11e7-80ca-37c9e6dd02fc.png)

This is the log from cloudformation

**Comment by moanany** [comment] 2017-11-29 05:05
Hey,

Thank you for the screenshot. It shows that the first error reported by CloudFormation (i.e. "lh-vid2 already exists") is what causes the stack creation to roll back. The name you specify for `FrameS3Bucket` must not be of an existing S3 bucket.

**Comment by moanany** [comment] 2017-11-29 16:00
You're welcome!

**Closed by moanany** 2017-11-29 16:00 UTC

**Comment by RooCoder** [comment] 2018-03-08 09:52
![image](https://user-images.githubusercontent.com/36875863/37144501-2db1f590-22b6-11e8-97c3-997b762c4808.png)
 my condition is similar I believe after following the steps. 
It is with the lambdaroles. Please help me where to delete/comment to make the build success
