### ISSUE TITLE
CF Template is giving problems

### ISSUE THREAD

**Issue by stardev24** [awslabs/amazon-rekognition-video-analyzer#4] opened 2017-10-14 18:30 UTC
It went well for initial steps.But If I am using  pynt createstack the stack is going to ROLLBACK_FAILED state and not finishing the remaing steps.And its showing rollback reason as Status reason:
The following resource(s) failed to delete: [EnrichedFrameTable].

**Comment by moanany** [comment] 2017-10-18 12:24
Duplicate of #3.

**Closed** 2017-10-18 12:23 UTC
